---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lynanextjs-v2                  # Ingress name
  labels:
    app: lynanextjs-v2
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "lynanextjs-v2.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lynanextjs-v2               # Links to Service name dynamically
                port:
                  number: 3000  # Links to service port dynamically
